### ISSUE TITLE
Set up database with PostgreSQL and Sequelize

### ISSUE THREAD

**Issue by raymondajaxmetrulis** [Team-New-Jersey/instafake#2]
Users table, Posts table, Comments table, Likes table

**Comment by raymondajaxmetrulis** [comment]
Need to wait for basic folder structure, but plan before

**Comment by sean21mcn** [comment]
Tables Info (1st Draft)

Users
user id (integer)
username (string) OR email (string)
password (string)
[full name (string)] -- optional



Posts
auto-generated image id (integer)
user id (foreign key integer)
description (string) -- [can be named something else]
timestamp (integer) [auto generated]



Comments
Username (foreign key string)
Comment (string)
Opt: timestamp (created at) [integer; auto generated]



Likes
Username (foreign key string)
Like (boolean)
Opt: timestamp (created at) [integer; auto generated]
